-- Who entered this.
--
-- The ledger has always recorded what happened and when, and never who. For a
-- single-person demo that is invisible; for a business with a bookkeeper, an
-- accountant and an owner it is the first question asked about any entry
-- somebody disagrees with, and "the system" is not an answer.
--
-- Two columns, because "which person" and "by what route" are different
-- questions with different uses. A figure keyed by hand at a desk, a figure
-- pushed by an integration, and a figure generated by the month-end close are
-- three different kinds of evidence, and only the first has somebody to ask.
--
-- Nullable, and deliberately so. Every entry that exists today was written
-- before this column did, and inventing an author for them would be inventing
-- evidence — the same class of mistake as inventing a historical exchange
-- rate. An entry with no author is one nobody recorded, which is the truth.

ALTER TABLE transactions ADD COLUMN created_by text;

--> statement-breakpoint
-- No foreign key to `user`.
--
-- Deleting a person must not be blocked by, or cascade into, the entries they
-- posted: the entries are the accounting record and they outlive the account.
-- A row here is a claim about who wrote it, and it stays true after the
-- account is closed. The join is a left join and the UI copes with a missing
-- name.
ALTER TABLE transactions ADD COLUMN created_via text NOT NULL DEFAULT 'unknown';

--> statement-breakpoint
ALTER TABLE transactions ADD CONSTRAINT transactions_created_via_check
  CHECK (created_via IN ('ui', 'api', 'system', 'import', 'unknown'));

--> statement-breakpoint
-- A person only exists on the routes a person uses. A cron-driven close and an
-- API key have no user behind them, and claiming one would be the invention
-- this column exists to avoid.
ALTER TABLE transactions ADD CONSTRAINT transactions_actor_check
  CHECK (created_by IS NULL OR created_via IN ('ui', 'api', 'import'));

--> statement-breakpoint
CREATE INDEX transactions_created_by_idx ON transactions (org_id, created_by, id)
  WHERE created_by IS NOT NULL;
