import { Pool } from 'pg';
import { drizzle } from 'drizzle-orm/node-postgres';
import { eq, sql } from 'drizzle-orm';
import * as schema from '../src/server/db/schema';
import { digestToken } from '../src/server/services/authentication';
import { newId } from '../src/lib/id';
import type { Database } from '../src/server/db/types';
import { checkTenantPolicies, TENANT_TABLE_COUNT, withTenant } from '../src/server/db/tenancy';
import { populateSampleLedger } from '../src/server/services/sample-ledger';
import { describeTarget, schemaConnectionString, sslFor } from './connection';

/**
 * Seeds a quarter's books for a Vietnamese stone exporter, as the read-only demo.
 *
 * The books themselves are `populateSampleLedger`, shared with "Try it with
 * sample data"; this script clears the database, creates the demo tenant and
 * the second one the isolation needs, registers the API key, and asserts the
 * result balances.
 */

async function main(): Promise<void> {
  const url = schemaConnectionString();
  const pool = new Pool({ connectionString: url, ssl: sslFor(url), max: 1 });
  console.log(`seeding ${describeTarget(url)}`);
  try {
    const database = drizzle(pool, { schema, casing: 'snake_case' }) as unknown as Database;

    // Seeding is destructive and must be explicit. Postings and entries are
    // append-only by trigger, so the triggers are lifted for the truncate.
    console.log('clearing existing data');
    // TRUNCATE does not fire row-level triggers, so the append-only guards
    // never see it — which is why this is a plain TRUNCATE and not a delete
    // with the triggers lifted. Naming them here would only create a
    // maintenance trap: `transactions_append_only` was replaced by
    // `transactions_guard_mutation` in 0004, and a stale ALTER would fail the
    // seed for a reason that has nothing to do with seeding.
    await database.execute(sql`
      TRUNCATE idempotency_keys, postings, transactions, accounting_periods,
               exchange_rates, accounts, api_keys, memberships, organizations
      RESTART IDENTITY CASCADE
    `);

    const demoSlug = process.env['DEMO_ORG_SLUG'] ?? 'demo';
    const orgId = newId('organization');
    await database
      .insert(schema.organizations)
      // Marked as *the* demo: that column, not the slug, is what makes a
      // ledger readable to a signed-out visitor. A partial unique index
      // allows exactly one, so "the demo" is never ambiguous.
      .values({
        id: orgId,
        name: 'Công ty TNHH Đá Bình Minh',
        slug: demoSlug,
        isDemo: true,
        // The books are kept in dong. Every export invoice is in a currency
        // that is not, which is what makes the balance rule interesting.
        functionalCurrency: 'VND',
        // A Vietnamese company's accountant does not get to invent account
        // codes, so the demo is on the statutory chart rather than a
        // convention — and the database enforces the digit rule.
        chartTemplate: 'vn_tt200',
        locale: 'vi',
      });

    // A second tenant with its own books exists purely so the isolation is
    // real rather than theoretical: there is something on the other side of
    // the policy for it to keep out.
    const otherOrgId = newId('organization');
    await database
      .insert(schema.organizations)
      .values({ id: otherOrgId, name: 'Second Tenant', slug: 'second' });

    // The demo tenant's API key is whatever LEDGER_API_TOKEN is set to, so a
    // deployment's existing credential keeps working and the token still
    // travels through the real api_keys lookup rather than a special case.
    const token = process.env['LEDGER_API_TOKEN'];
    if (token && token.length < 32) {
      // A short token is guessable, and a placeholder like the one an example
      // file suggests is a credential anyone who has read the file holds.
      throw new Error(
        'LEDGER_API_TOKEN is shorter than 32 characters. Generate one with `openssl rand -hex 32`.',
      );
    }
    if (token) {
      await database.insert(schema.apiKeys).values({
        id: newId('apiKey'),
        orgId,
        name: 'seeded demo key',
        tokenDigest: digestToken(token),
        // A supplied token is not generated by `issueToken`, so its prefix is
        // taken from the token itself — six characters, enough to tell keys
        // apart on the settings page and too few to help anyone guess one.
        tokenPrefix: token.slice(0, 6),
      });
      console.log('registered LEDGER_API_TOKEN as the demo tenant key');
    } else {
      console.log('LEDGER_API_TOKEN not set; no API key registered (reads still work)');
    }
    const { entries } = await populateSampleLedger(database, orgId, {
      log: (line) => console.log(line),
    });

    const policies = await checkTenantPolicies(database);
    if (!policies.configured) {
      throw new Error(
        `tenant isolation is not configured: ${policies.tablesWithRls}/${TENANT_TABLE_COUNT} tables with RLS, ` +
          `${policies.tablesForced}/${TENANT_TABLE_COUNT} forced, ${policies.policies} policies`,
      );
    }
    console.log(
      `tenant isolation: ${policies.tablesForced}/${TENANT_TABLE_COUNT} tables forced, ${policies.policies} policies`,
    );

    // The seed asserts its own output: if the books do not balance, the script
    // fails rather than leaving a broken ledger behind for the UI to render.

    const residual = await withTenant(database, orgId, async (tx) => {
      const [row] = await tx
        // Summed in the *functional* currency.
        //
        // `balance_minor` is in each account's own currency, so adding a
        // dollar balance to a dong one produces a number with no meaning —
        // which is what this assertion used to do, and it only ever looked
        // right because every account was USD.
        .select({
          residual: sql<string>`coalesce(sum(${schema.accounts.baseBalanceMinor}), 0)::text`,
        })
        .from(schema.accounts);
      return row?.residual;
    });

    const [pendingCount] = await withTenant(database, orgId, async (tx) => {
      const rows = await tx
        .select({ count: sql<string>`count(*)::text` })
        .from(schema.transactions)
        .where(eq(schema.transactions.status, 'pending'));
      return rows;
    });
    console.log(`posted ${entries} entries (${pendingCount?.count ?? 0} left pending)`);
    console.log(`trial balance residual: ${residual ?? 'unknown'} (0 means consistent)`);
    if (residual !== '0') throw new Error('seeded ledger does not balance');
  } finally {
    await pool.end();
  }
}

main().catch((error: unknown) => {
  console.error('seed failed', error);
  process.exitCode = 1;
});
