/**
 * Types for `import picture from './x.png'`.
 *
 * `next-env.d.ts` carries this same reference, but it is generated by `next
 * dev` and `next build` and ignored by git, and CI type-checks a fresh
 * checkout before it builds — so the landing page's screenshot import
 * type-checked on every machine that had run the app once, and failed on
 * the one that matters.
 */
/// <reference types="next/image-types/global" />
