import type { LedgerError } from '@/server/domain/errors';

/**
 * One representative of every variant. Adding a `LedgerError` without adding it
 * here is a type error, which is the point: a new failure mode must arrive with
 * a title, a description and a status, not with `undefined` in an API response.
 *
 * Shared rather than kept in `errors.test.ts` because the dashboard renders the
 * same variants in three languages, and a second sample map would be a second
 * list for the next variant to be forgotten from.
 */
export const EVERY_VARIANT: Record<LedgerError['code'], LedgerError> = {
  account_not_found: { code: 'account_not_found', accountId: 'acct_x' },
  account_closed: { code: 'account_closed', accountId: 'acct_x' },
  currency_mismatch: { code: 'currency_mismatch', expected: 'EUR', received: 'USD' },
  unbalanced_transaction: {
    code: 'unbalanced_transaction',
    residual: '0.01',
    currency: 'USD',
  },
  too_few_postings: { code: 'too_few_postings', count: 1 },
  zero_amount_posting: { code: 'zero_amount_posting', index: 2 },
  duplicate_account_in_transaction: {
    code: 'duplicate_account_in_transaction',
    accountId: 'acct_x',
  },
  insufficient_funds: {
    code: 'insufficient_funds',
    accountId: 'acct_x',
    available: '10.00',
    requested: '25.00',
    currency: 'USD',
  },
  idempotency_key_reused: { code: 'idempotency_key_reused', key: 'k' },
  entry_not_found: { code: 'entry_not_found', transactionId: 'txn_x' },
  already_reversed: {
    code: 'already_reversed',
    transactionId: 'txn_x',
    reversedBy: 'txn_y',
  },
  entry_not_settled: {
    code: 'entry_not_settled',
    transactionId: 'txn_x',
    entryStatus: 'archived',
  },
  invalid_status_transition: {
    code: 'invalid_status_transition',
    transactionId: 'txn_x',
    from: 'posted',
    to: 'archived',
  },
  stale_account_version: {
    code: 'stale_account_version',
    accountId: 'acct_x',
    expected: 3,
    actual: 5,
  },
  endpoint_not_found: { code: 'endpoint_not_found', endpointId: 'whe_x' },
  endpoint_url_taken: { code: 'endpoint_url_taken', url: 'https://hooks.example.com/ledger' },
  delivery_not_found: { code: 'delivery_not_found', deliveryId: 'whd_x' },
  period_already_closed: { code: 'period_already_closed', periodMonth: '2026-08-01' },
  period_not_closed: { code: 'period_not_closed', periodMonth: '2026-08-01' },
  period_not_finished: { code: 'period_not_finished', periodMonth: '2026-09-01' },
  earlier_period_open: {
    code: 'earlier_period_open',
    periodMonth: '2026-08-01',
    open: '2026-07-01',
  },
  retained_earnings_missing: { code: 'retained_earnings_missing' },
  fx_rate_required: {
    code: 'fx_rate_required',
    accountId: 'acct_x',
    currency: 'USD',
    functional: 'VND',
  },
  invalid_fx_rate: { code: 'invalid_fx_rate', accountId: 'acct_x', rate: 'abc' },
  rate_not_found: { code: 'rate_not_found', base: 'USD', quote: 'VND' },
  fx_account_missing: { code: 'fx_account_missing' },
  revaluation_required: {
    code: 'revaluation_required',
    periodMonth: '2026-08-01',
    accounts: ['Vietcombank USD'],
  },
  amount_not_representable: {
    code: 'amount_not_representable',
    accountId: 'acct_x',
    amount: '10.005',
    currency: 'USD',
  },
  currency_imbalance: { code: 'currency_imbalance', currency: 'USD', residual: '1.00' },
  item_not_found: { code: 'item_not_found', itemId: 'item_x' },
  item_archived: { code: 'item_archived', itemId: 'item_x' },
  sku_taken: { code: 'sku_taken', sku: 'GRN-60x60' },
  insufficient_stock: {
    code: 'insufficient_stock',
    itemId: 'item_x',
    requested: '24687',
    available: '12000',
    precision: 3,
    unit: 't',
  },
  cost_layer_not_found: { code: 'cost_layer_not_found', layerId: 'layer_x' },
  cost_layer_required: { code: 'cost_layer_required', itemId: 'item_x' },
  costing_method_not_permitted: {
    code: 'costing_method_not_permitted',
    method: 'lifo',
    chartTemplate: 'vn_tt200',
  },
  inventory_account_not_functional: {
    code: 'inventory_account_not_functional',
    accountId: 'acct_x',
    currency: 'USD',
    functional: 'VND',
  },
  account_wrong_type: {
    code: 'account_wrong_type',
    accountId: 'acct_x',
    expected: 'asset',
    actual: 'revenue',
  },
  shipment_reference_taken: { code: 'shipment_reference_taken', reference: 'CONT-4417' },
  shipment_not_found: { code: 'shipment_not_found', shipmentId: 'ship_x' },
  shipment_has_no_stock: { code: 'shipment_has_no_stock', shipmentId: 'ship_x' },
  mixed_units: { code: 'mixed_units', units: ['m2', 'tonne'] },
  weight_missing: { code: 'weight_missing', layerIds: ['layer_a'] },
  debit_account_required: { code: 'debit_account_required' },
  tax_code_name_taken: { code: 'tax_code_name_taken', name: 'GTGT 10%' },
  tax_code_not_found: { code: 'tax_code_not_found', taxCodeId: 'tax_x' },
  sales_tax_is_not_reclaimable: { code: 'sales_tax_is_not_reclaimable' },
  tax_account_missing: { code: 'tax_account_missing', treatment: 'vat', side: 'input' },
  period_already_filed: { code: 'period_already_filed', periodMonth: '2026-03-01' },
  tax_payable_account_missing: { code: 'tax_payable_account_missing' },
  nothing_to_file: { code: 'nothing_to_file', periodStart: '2026-03-01', periodEnd: '2026-03-31' },
  earlier_return_unfiled: {
    code: 'earlier_return_unfiled',
    periodMonth: '2026-03-01',
    unfiled: '2026-02-01',
  },
  entry_owned_by_stock: {
    code: 'entry_owned_by_stock',
    transactionId: 'txn_1',
    source: 'inventory',
  },
  sale_has_no_lines: { code: 'sale_has_no_lines' },
  sale_reference_taken: { code: 'sale_reference_taken', reference: 'INV-2607' },
  credit_note_reference_taken: { code: 'credit_note_reference_taken', reference: 'CN-0001' },
  credit_note_not_found: { code: 'credit_note_not_found', creditNoteId: 'cn_x' },
  credit_note_has_no_lines: { code: 'credit_note_has_no_lines' },
  credit_line_not_on_sale: {
    code: 'credit_line_not_on_sale',
    saleId: 'sale_x',
    movementId: 'move_x',
  },
  credit_line_repeated: { code: 'credit_line_repeated', movementId: 'move_x' },
  credit_exceeds_sale: {
    code: 'credit_exceeds_sale',
    limit: 'quantity',
    movementId: 'move_x',
    sku: 'PAV-600',
    remaining: '4000',
    requested: '5000',
    precision: 2,
    unit: 'm2',
  },
  credit_before_sale: {
    code: 'credit_before_sale',
    creditedOn: '2026-09-01',
    invoicedOn: '2026-09-10',
  },
  supplier_return_reference_taken: { code: 'supplier_return_reference_taken', reference: 'RTV-01' },
  supplier_return_not_found: { code: 'supplier_return_not_found', supplierReturnId: 'sret_x' },
  supplier_refund_exceeds_lot: {
    code: 'supplier_refund_exceeds_lot',
    layerId: 'layer_x',
    remaining: '1200.00',
    requested: '1500.00',
    currency: 'USD',
  },
  supplier_return_before_receipt: {
    code: 'supplier_return_before_receipt',
    returnedOn: '2026-09-01',
    receivedOn: '2026-09-10',
  },
  supplier_return_tax_needs_local_currency: {
    code: 'supplier_return_tax_needs_local_currency',
    currency: 'USD',
    functional: 'VND',
  },
  supplier_account_required: { code: 'supplier_account_required', layerId: 'layer_x' },
  supplier_return_exceeds_lot: {
    code: 'supplier_return_exceeds_lot',
    layerId: 'layer_x',
    remaining: '78300',
    requested: '100000',
    precision: 2,
    unit: 'm2',
  },
  document_not_found: { code: 'document_not_found', documentId: 'doc_x' },
  document_link_not_found: { code: 'document_link_not_found', linkId: 'dlink_x' },
  document_empty: { code: 'document_empty' },
  document_too_large: { code: 'document_too_large', sizeBytes: 6_000_000, limitBytes: 4_194_304 },
  document_type_not_allowed: { code: 'document_type_not_allowed', filename: 'invoice.html' },
  bank_account_not_reconcilable: { code: 'bank_account_not_reconcilable', accountId: 'acct_x' },
  bank_line_not_found: { code: 'bank_line_not_found', lineId: 'bline_x' },
  bank_statement_unreadable: { code: 'bank_statement_unreadable', missing: ['date', 'amount'] },
  bank_statement_has_problems: { code: 'bank_statement_has_problems', rows: [2, 5] },
  bank_line_already_matched: { code: 'bank_line_already_matched', lineId: 'bline_x' },
  bank_posting_already_matched: { code: 'bank_posting_already_matched', postingId: 'post_x' },
  bank_line_not_matched: { code: 'bank_line_not_matched', lineId: 'bline_x' },
  bank_match_amount_mismatch: {
    code: 'bank_match_amount_mismatch',
    lineAmount: '-12.50',
    postingAmount: '-12.05',
    currency: 'AUD',
  },
  bank_posting_not_on_account: { code: 'bank_posting_not_on_account', postingId: 'post_x' },
  einvoice_seller_incomplete: { code: 'einvoice_seller_incomplete', missing: ['taxId', 'series'] },
  einvoice_series_year: { code: 'einvoice_series_year', series: 'C25TBM', year: '2026' },
  einvoice_already_issued: { code: 'einvoice_already_issued', einvoiceId: 'einv_x' },
  einvoice_original_missing: { code: 'einvoice_original_missing', saleId: 'sale_x' },
  einvoice_not_found: { code: 'einvoice_not_found', einvoiceId: 'einv_x' },
  tax_id_invalid: { code: 'tax_id_invalid', taxId: '12345' },
  sale_not_found: { code: 'sale_not_found', saleId: 'sale_1' },
  due_before_invoice: { code: 'due_before_invoice', dueOn: '2025-03-01', invoicedOn: '2026-03-01' },
  account_code_required: { code: 'account_code_required', chartTemplate: 'vn_tt200' },
  account_code_disagrees: { code: 'account_code_disagrees', accountCode: '511', type: 'asset' },
  account_code_taken: { code: 'account_code_taken', accountCode: '1311' },
  open_items_not_permitted: { code: 'open_items_not_permitted', type: 'revenue' },
  payment_terms_need_open_items: { code: 'payment_terms_need_open_items' },
};
